title: Razertory's Blog
description: Posts of Razertory
author: Razertory
github: https://github.com/razertory
about: Rust, Go, Ruby
disqus_shortname: razertory
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-github
      link: "https://github.com/razertory"
    - icon: fa-twitter
      link: "https://twitter.com/razertory"

share:
  twitter_username: razertory

urls:
    - text: About Me
      url: /about/
    #- text: My Projects
    #  url: /projects/
    - text: Collections
      url: /collections
    # - text: XML Feed
    #   url: /feed.xml

url: "http://razertory.me"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
